In [1]:
# ============================================================
# Q4 — Missingness Indicator + Logistic Regression
# ============================================================

import numpy as np
import pandas as pd

from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split

from sklearn.pipeline import Pipeline

from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import roc_auc_score


# ------------------------------------------------------------
# 1. Load classification dataset
# ------------------------------------------------------------

data = load_breast_cancer()

X = pd.DataFrame(
    data.data,
    columns=data.feature_names
)

y = data.target


print("Original shape:", X.shape)

Original shape: (569, 30)

In [2]:
# ------------------------------------------------------------
# 2. Artificially introduce missing values
# ------------------------------------------------------------

rng = np.random.RandomState(42)

X_missing = X.copy()

missing_rate = 0.10

mask = rng.rand(*X_missing.shape) < missing_rate

X_missing[mask] = np.nan


# ------------------------------------------------------------
# 3. Check missingness
# ------------------------------------------------------------

print("\nMissing percentage:")

print(
    X_missing.isnull().mean()
    .mul(100)
    .sort_values(ascending=False)
)

Missing percentage:
worst fractal dimension    14.586995
mean concave points        14.235501
mean texture               12.478032
mean concavity             12.126538
concave points error       11.423550
texture error              11.247803
smoothness error           11.247803
worst perimeter            11.072056
worst radius               10.896309
area error                 10.720562
worst compactness          10.544815
mean area                  10.544815
mean perimeter             10.369069
fractal dimension error    10.369069
mean radius                 9.841828
worst symmetry              9.841828
compactness error           9.666081
concavity error             9.666081
mean compactness            9.666081
mean fractal dimension      9.666081
mean symmetry               9.666081
perimeter error             9.666081
worst smoothness            9.490334
symmetry error              9.314587
worst texture               9.314587
radius error                9.138840
worst concavity             8.787346
mean smoothness             8.084359
worst concave points        8.084359
worst area                  7.381371
dtype: float64

In [3]:
# ------------------------------------------------------------
# 4. Train/test split
# ------------------------------------------------------------

X_train, X_test, y_train, y_test = train_test_split(
    X_missing,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)


# ============================================================
# MODEL A — MEDIAN ONLY
# ============================================================

median_pipeline = Pipeline([
    
    (
        "imputer",
        SimpleImputer(
            strategy="median"
        )
    ),
    
    (
        "model",
        LogisticRegression(
            max_iter=5000
        )
    )
])

In [4]:
# ------------------------------------------------------------
# 5. Train model
# ------------------------------------------------------------

median_pipeline.fit(
    X_train,
    y_train
)


# ------------------------------------------------------------
# 6. Predict
# ------------------------------------------------------------

median_probabilities = (
    median_pipeline
    .predict_proba(X_test)[:, 1]
)


# ------------------------------------------------------------
# 7. AUC
# ------------------------------------------------------------

median_auc = roc_auc_score(
    y_test,
    median_probabilities
)

print("\nMedian-only AUC:")
print(median_auc)

Median-only AUC:
0.9877645502645502

In [5]:
# ------------------------------------------------------------
# 8. Extract coefficients
# ------------------------------------------------------------

median_coefficients = (
    median_pipeline
    .named_steps["model"]
    .coef_[0]
)


coef_without_indicator = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": median_coefficients
})

print("\nCoefficients WITHOUT missingness indicators:")
display(coef_without_indicator)

Coefficients WITHOUT missingness indicators:

                    Feature  Coefficient
0               mean radius     0.317671
1              mean texture    -0.031726
2            mean perimeter     0.012240
3                 mean area     0.001240
4           mean smoothness    -0.224947
5          mean compactness    -0.437646
6            mean concavity    -0.706107
7       mean concave points    -0.331815
8             mean symmetry    -0.272306
9    mean fractal dimension    -0.050044
10             radius error    -0.054452
11            texture error     0.434012
12          perimeter error    -0.125275
13               area error    -0.052737
14         smoothness error    -0.014865
15        compactness error     0.021872
16          concavity error    -0.046299
17     concave points error    -0.030551
18           symmetry error    -0.044470
19  fractal dimension error     0.007684
20             worst radius    -0.376409
21            worst texture    -0.227071
22          worst perimeter    -0.091968
23               worst area    -0.004514
24         worst smoothness    -0.389443
25        worst compactness    -1.460940
26          worst concavity    -2.289594
27     worst concave points    -0.781425
28           worst symmetry    -1.036965
29  worst fractal dimension    -0.150102

In [6]:

# ============================================================
# MODEL B — MEDIAN + MISSINGNESS INDICATOR
# ============================================================

indicator_pipeline = Pipeline([
    
    (
        "imputer",
        SimpleImputer(
            strategy="median",
            add_indicator=True
        )
    ),
    
    (
        "model",
        LogisticRegression(
            max_iter=5000
        )
    )
])


# ------------------------------------------------------------
# 9. Train model
# ------------------------------------------------------------

indicator_pipeline.fit(
    X_train,
    y_train
)


# ------------------------------------------------------------
# 10. Predict
# ------------------------------------------------------------

indicator_probabilities = (
    indicator_pipeline
    .predict_proba(X_test)[:, 1]
)

In [7]:
# ------------------------------------------------------------
# 11. AUC
# ------------------------------------------------------------

indicator_auc = roc_auc_score(
    y_test,
    indicator_probabilities
)

print("\nMedian + Indicator AUC:")
print(indicator_auc)


# ============================================================
# 12. Extract coefficients
# ============================================================

indicator_coefficients = (
    indicator_pipeline
    .named_steps["model"]
    .coef_[0]
)


# ------------------------------------------------------------
# 13. Get names of generated features
# ------------------------------------------------------------

imputer = (
    indicator_pipeline
    .named_steps["imputer"]
)

indicator_features = (
    imputer
    .get_feature_names_out(X.columns)
)


coef_with_indicator = pd.DataFrame({
    "Feature": indicator_features,
    "Coefficient": indicator_coefficients
})


print("\nCoefficients WITH missingness indicators:")

display(coef_with_indicator)

Median + Indicator AUC:
0.9811507936507937

Coefficients WITH missingness indicators:

                                     Feature  Coefficient
0                                mean radius     0.367857
1                               mean texture    -0.049077
2                             mean perimeter     0.010173
3                                  mean area     0.002649
4                            mean smoothness    -0.203068
5                           mean compactness    -0.413443
6                             mean concavity    -0.632990
7                        mean concave points    -0.294320
8                              mean symmetry    -0.254213
9                     mean fractal dimension    -0.054110
10                              radius error    -0.066047
11                             texture error     0.747860
12                           perimeter error    -0.205484
13                                area error    -0.055421
14                          smoothness error    -0.012082
15                         compactness error     0.011490
16                           concavity error    -0.073136
17                      concave points error    -0.028749
18                            symmetry error    -0.028043
19                   fractal dimension error     0.005531
20                              worst radius    -0.426423
21                             worst texture    -0.249176
22                           worst perimeter    -0.104604
23                                worst area    -0.004596
24                          worst smoothness    -0.353239
25                         worst compactness    -1.431495
26                           worst concavity    -2.206145
27                      worst concave points    -0.679360
28                            worst symmetry    -0.977377
29                   worst fractal dimension    -0.144019
30              missingindicator_mean radius    -0.074736
31             missingindicator_mean texture     0.160031
32           missingindicator_mean perimeter    -0.228330
33                missingindicator_mean area     0.532425
34          missingindicator_mean smoothness    -0.441481
35         missingindicator_mean compactness    -0.443088
36           missingindicator_mean concavity     0.479749
37      missingindicator_mean concave points    -0.578981
38            missingindicator_mean symmetry    -0.620500
39   missingindicator_mean fractal dimension    -0.755881
40             missingindicator_radius error     0.411374
41            missingindicator_texture error     0.123272
42          missingindicator_perimeter error    -0.468192
43               missingindicator_area error     0.434481
44         missingindicator_smoothness error    -0.390599
45        missingindicator_compactness error     0.716340
46          missingindicator_concavity error    -0.477893
47     missingindicator_concave points error    -0.708004
48           missingindicator_symmetry error    -0.140340
49  missingindicator_fractal dimension error     0.009934
50             missingindicator_worst radius    -0.530162
51            missingindicator_worst texture    -0.112271
52          missingindicator_worst perimeter    -0.022355
53               missingindicator_worst area    -0.855526
54         missingindicator_worst smoothness    -0.228358
55        missingindicator_worst compactness     0.231945
56          missingindicator_worst concavity    -0.391658
57     missingindicator_worst concave points     0.045110
58           missingindicator_worst symmetry    -0.549174
59  missingindicator_worst fractal dimension    -0.747886

In [8]:
# ============================================================
# 14. Display only indicator coefficients
# ============================================================

indicator_rows = (
    coef_with_indicator[
        coef_with_indicator["Feature"]
        .str.contains("missingindicator")
    ]
)

print("\nMissingness Indicator Coefficients:")

display(indicator_rows)

Missingness Indicator Coefficients:

                                     Feature  Coefficient
30              missingindicator_mean radius    -0.074736
31             missingindicator_mean texture     0.160031
32           missingindicator_mean perimeter    -0.228330
33                missingindicator_mean area     0.532425
34          missingindicator_mean smoothness    -0.441481
35         missingindicator_mean compactness    -0.443088
36           missingindicator_mean concavity     0.479749
37      missingindicator_mean concave points    -0.578981
38            missingindicator_mean symmetry    -0.620500
39   missingindicator_mean fractal dimension    -0.755881
40             missingindicator_radius error     0.411374
41            missingindicator_texture error     0.123272
42          missingindicator_perimeter error    -0.468192
43               missingindicator_area error     0.434481
44         missingindicator_smoothness error    -0.390599
45        missingindicator_compactness error     0.716340
46          missingindicator_concavity error    -0.477893
47     missingindicator_concave points error    -0.708004
48           missingindicator_symmetry error    -0.140340
49  missingindicator_fractal dimension error     0.009934
50             missingindicator_worst radius    -0.530162
51            missingindicator_worst texture    -0.112271
52          missingindicator_worst perimeter    -0.022355
53               missingindicator_worst area    -0.855526
54         missingindicator_worst smoothness    -0.228358
55        missingindicator_worst compactness     0.231945
56          missingindicator_worst concavity    -0.391658
57     missingindicator_worst concave points     0.045110
58           missingindicator_worst symmetry    -0.549174
59  missingindicator_worst fractal dimension    -0.747886

In [9]:
# ============================================================
# 15. Compare AUC
# ============================================================

auc_comparison = pd.DataFrame({
    
    "Model": [
        "Median Only",
        "Median + Missing Indicator"
    ],
    
    "AUC": [
        median_auc,
        indicator_auc
    ]
})

print("\nAUC Comparison:")

display(auc_comparison)

AUC Comparison:

                        Model       AUC
0                 Median Only  0.987765
1  Median + Missing Indicator  0.981151